services:
    _defaults:
        autowire: true
        autoconfigure: true

    Donut\Domain\Donut\Repository\Donuts:
        alias: 'Donut\Tests\Behat\Repository\InMemoryDonuts'

    Donut\Tests\Behat\:
        resource: '../tests/Behat'
